### ISSUE TITLE
react-router 关于加载提示的疑惑

### ISSUE THREAD

**Issue by cobish** [awaw00/react-how-can-i#1]
我用了 webpack 将不同的页面分块 chunk 打包，因为以前用 react 的 componentWillMount 来显示 `加载中` 的提示，但是现在有个问题就是 chunk js 在下载期间组件的代码还没下载完，所以 `componentWillMount` 方法还触发不了，所以页面显示空白（并没有 `加载中` 的提示），请问是否有办法处理，谢谢！

**Comment by awaw00** [comment]
可以在getComponent方法里进行一些处理来展示加载的提示，具体实现等我研究研究

**Comment by awaw00** [comment]
@cobish 具体实现在这里，可以参考一下：http://codepen.io/awaw00/pen/KgrpPw?editors=0010

在容器组件（App）里注册了一个componentOnLoading的事件，当Router的getComponent被调用的时候触发这个事件并改变父组件（App）里的state.loading，来展示加载提示。当组件加载完毕后，App的ComponentWillReceiveProps会被调用，在这里将state.loading设为false。

有其它的思路都可以交流一下～

**Comment by cobish** [comment]
@awaw00 好的，我尝试一下，感谢你的回复，中秋快乐！

**Comment by awaw00** [comment]
@cobish 中秋快乐😄
