### ISSUE TITLE
reselect 使用

### ISSUE THREAD

**Issue by vritser** [awaw00/react-how-can-i#2]
请讲一下 什么时候要使用reselect(最好举个例子) 谢谢

**Comment by awaw00** [comment]
@vritser 感谢分享，之前都没发现有这么个好东西~
粗略地看了一下Readme，reselect可以帮助我们从一个对象或Redux的Store中获取你所需要的数据，并且在此之上提供了一些高级特性：
1. 高效率，使用 Memoized Selectors 避免某些情况下会出现的重复计算（主要指使用Redux Connect的React组件因非Store数据更新而造成的rerender的时候），帮助提高应用性能；
2. 可组合，多个selector可以组合使用，减少重复代码，提高项目可维护性。

关于例子，我觉得官方的[Example](https://github.com/reactjs/reselect#example)已经是非常简洁明了了，可以仔细看一看。

关于reselect的应用场景，就如上面所说的，如果你的项目使用了Redux，你的组件对Store中的数据依赖非常多，Store的节点很广很深，并且在mapStateToProps中对store的数据进行了计算和转换操作，那么使用reselect可以有效地提高应用的效率，而且可以通过合理地组织selectors，提升项目的可维护性和健壮性。

发现Redux文档中也有对reselect的介绍：[计算衍生数据](http://cn.redux.js.org/docs/recipes/ComputingDerivedData.html)

假期结束赶着回杭州，到家了才看到，非常抱歉。

**Comment by vritser** [comment]
抱歉 没有及时回复。 非常感谢
