### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by leedstyh** [awaw00/react-how-can-i#3]
如何做类似twitter那样的，【文章列表页】点某个文章，然后弹出个【文章详情】的modal，url也跟着变化，然后按浏览器后退键，文章详情的modal消失，然后url回退到之前的状态，但是列表页不会重新刷新

**Comment by awaw00** [comment]
【改变URL并且不刷新页面】这个可以使用 history API 来完成，文档看这里：[操纵浏览器的历史记录](https://developer.mozilla.org/zh-CN/docs/DOM/Manipulating_the_browser_history)

如果用 React 和 React Router 来实现的话，可以这么做：
- 在Router的配置里，设置【文章列表页】这个路由的 Component 为文章列表页这个组件
- 给【文章列表页】这个路由添加一个【文章详情】的子路由，子路由的 Component 为文章详情的组件

比如说：

``` javascript
<Router history={browserHistory}>
  <Route path="/articles" component={ArticleListComponent}>
    <Route path=":articleId" component={ArticleDetailComponent} />
  </Route>
</Router>
```

然后，在 ArticleListComponent 组件中的render方法中适当的地方加入 {this.props.children}：

``` javascript
// ArticleListComponent.js
class ArticleListComponent extends Component {
  render () {
    return (
      <div>
        ...
        {this.props.children}
      </div>
    );
  }
}
```

这样，在进入【文章详情】的路由的时候，ArticleDetailComponent 组件就会被渲染出来了。

同样的，当按浏览器后退按钮的时候，又会回到文章列表的路由，ArticleDetailComponent 就会被卸载了。

**Comment by leedstyh** [comment]
Thanks，我研究一下
