### ISSUE TITLE
react-router

### ISSUE THREAD

**Issue by whevether** [awaw00/react-how-can-i#4]
react-router 客户端配置好的路由如何在服务端渲染。 框架用的是express ，能否给个demo看看，我现在就卡在服务端路由快了。因为服务端express 有自己的套路由系统;

**Comment by awaw00** [comment]
@whevether 服务端渲染暂时还没接触过，等我有时间研究一下再和你讨论讨论。

**Comment by awaw00** [comment]
@whevether 非常抱歉，最近才有时间闲下来研究SSR，发现一个比较好的example [universal-hmr-ssr-react-redux](https://github.com/Alex-ray/universal-hmr-ssr-react-redux)，你可以clone到本地跑起来看看，有什么问题再问我。
