### ISSUE TITLE
router的histroy属性和route的path属性能讲解下吗

### ISSUE THREAD

**Issue by scc02** [awaw00/react-how-can-i#5]
import React from 'react'
import { render } from 'react-dom'
import { Router, Route, browserHistory, IndexRoute } from 'react-router'
import App from './modules/App'
import About from './modules/About'
import Repos from './modules/Repos'
import Repo from './modules/Repo'
import Home from './modules/Home'

render((
  <Router history={browserHistory}>
    <Route path="/" component={App}>
      <IndexRoute component={Home}/>
      <Route path="/repos" component={Repos}>
        <Route path="/repos/:userName/:repoName" component={Repo}/>
      </Route>
      <Route path="/about" component={About}/>
    </Route>
  </Router>
), document.getElementById('app'))

**Comment by awaw00** [comment]
- React Router 中的 History：[文档](https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md)
- React Router 依赖的 history ：[文档](https://github.com/mjackson/history/blob/master/README.md)
- React Router 的 path 配置：[文档](https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteConfiguration.md)
